pull_request_rules:
  - name: Automated merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=build
      - status-success=lint
    actions:
      merge:
        method: merge
      label:
        add: ['chore(deps):', '🛠 Improvement']

  - name: Automated dependabot merge pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build
      - status-success=lint
    actions:
      merge:
        method: merge
      label:
        add: ['chore(deps):', '🛠 Improvement']
